version: "3"
services:
  hacker_news_db:
    image: mongo:4.0
    container_name: "hacker_news_db"
    ports:
      - 27017:27017
    restart: always
  hacker_news_api:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - hacker_news_db
